[package]
name = "url_shortener"
version = "0.1.0"
authors = ["john"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "url_shortener"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
url = "2.5.4"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
sqlx = { version = "0", features = ["runtime-actix-native-tls", "postgres"] }
runtime = "0.0.0"
sha2 = "0.10.8"
base64 = "0.22.1"

[dev-dependencies]
reqwest = "0.12.12"
