# docker-compose -f stack.yml up
# https://crates.io/crates/sqlx

services:
  db:
    image: postgres:17-alpine
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Runs at first startup
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080