name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust (beta - edition 2024 ) - remove this when 1.85 releases to stable -
      uses: actions-rs/toolchain@v1
      with:
        toolchain: beta
        override: true
    - name: Build
      run: cargo build -q
    - name: Run tests
      run: cargo test